source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'BSGridCollectionViewLayout_Example' do
  pod "BSGridCollectionViewLayout", :path => "../"
end

target 'BSGridCollectionViewLayout_Tests' do
  pod "BSGridCollectionViewLayout", :path => "../"
end

